### PR TITLE
Fixed translation issues

### PR DESCRIPTION
**Pull request by GalacitCity**
Fixed Chinese translation issues

### CODE REVIEW

**Comment by HaHaWTH** [comment]
i think we can merge 2 PRs into one and this makes merging PR easier,also can get benefits from 2 translations,OK?

**Comment by GalacitCity** [comment]
> i think we can merge 2 PRs into one and this makes merging PR easier,also can get benefits from 2 translations,OK?

Sure,But there is something wrong with your translation

**Comment by igentuman** [comment]
Guys, i don't know how to resolve the conflict. Can you do it?

**Comment by HaHaWTH** [comment]
> Guys, i don't know how to resolve the conflict. Can you do it?

Sure,and the translation problem is fixed now,thanks for your feedback!❤

**Comment by GalacitCity** [comment]
> > Guys, i don't know how to resolve the conflict. Can you do it?
> 
> Sure,and the translation problem is fixed now,thanks for your feedback!❤

我想他不是这个意思
I don't think he meant that...

**Comment by HaHaWTH** [comment]
> > > Guys, i don't know how to resolve the conflict. Can you do it?
> > 
> > 
> > Sure,and the translation problem is fixed now,thanks for your feedback!❤
> 
> 我想他不是这个意思 I don't think he meant that...
Ive replied the wrong man,haha

**Comment by GalacitCity** [comment]
> Guys, i don't know how to resolve the conflict. Can you do it?

You may need to delete old translation files,I think.

**Comment by GalacitCity** [comment]
> 

Uh..all right

**Comment by HaHaWTH** [comment]
> > Guys, i don't know how to resolve the conflict. Can you do it?
> 
> You may need to delete old translation files,I think.

Additions and deletions in 2 translation files causes the conflict,maybe

**Comment by HaHaWTH** [comment]
> > 
> 
> Uh..all right

I think we should merge two versions of translation files first,then open the PR,can you leave a contact information like QQ number?

**Comment by GalacitCity** [comment]
> 

OK,My qq number is 226935179

**Pull request closed without merging**
